export const CHANGE_MOVIES_TAB = "CHANGE_MOVIES_TAB";
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIE_SUBJECT = "FETCH_MOVIE_SUBJECT";
export const CHANGE_LOADING_STATUS = "CHANGE_LOADING_STATUS";
